---
- name: Configurar servidor NFS en CentOS
  hosts: webserver
  become: true

  tasks:
    - name: Instalar NFS y firewalld
      dnf:
        name:
          - nfs-utils
          - firewalld
        state: present

    - name: Iniciar y habilitar servicios NFS y firewalld
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - nfs-server

    - name: Crear carpeta para compartir
      file:
        path: /var/nfs_shared
        state: directory
        owner: nobody
        group: nobody
        mode: '0777'

    - name: Configurar /etc/exports
      lineinfile:
        path: /etc/exports
        line: "/var/nfs_shared *(rw,sync,no_subtree_check,no_root_squash)"
        state: present
      notify: recargar exports

    - name: Abrir puerto 2049 en firewalld
      firewalld:
        port: 2049/tcp
        permanent: yes
        state: enabled
        immediate: yes

  handlers:
    - name: recargar exports
      command: exportfs -ra
